[[main]]
none = "none"

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "sPIKFWMGHz"
weight = 1

[[main]]
name = "About"
pageRef = "about"
identifier = "dSj61kfV4h"
weight = 9999

[[footer]]
none = "none"
